//
//  Homeless.swift
//  FinalProjectApp
//
//  Created by Scholar on 7/18/24.
//

import SwiftUI
struct Homeless: View {
  var body: some View {
    ZStack{
      Color.init(red: 253/255, green: 233/255, blue: 234/255)
        .edgesIgnoringSafeArea(/*@START_MENU_TOKEN@*/.all/*@END_MENU_TOKEN@*/)
      ScrollView {
        VStack{
          Text("Get involved and fight against food insecurity!🥪")
            .font(.title)
            .fontWeight(.bold)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .multilineTextAlignment(.center)
            .fixedSize(horizontal: false, vertical: true)
            .padding()
          Text("Food Bank of Deleware")
            .font(.subheadline)
            .fontWeight(.bold)
            .font(.title)
            .fontWeight(.bold)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .multilineTextAlignment(.center)
            .padding()
          Text("The Food Bank of Deleware is a is a food service that serves the homeless and less fortunate while working on long-term solutions to hunger and poverty.")
            .font(.caption)
            .multilineTextAlignment(.center)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .fixedSize(horizontal: false, vertical: true)
            .padding()
          Text("Get Started: Visit https://www.fbd.org/ for more info!")
            .font(.caption)
            .multilineTextAlignment(.center)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .padding()
          Text("Change 4 Good Inc.")
            .font(.subheadline)
            .fontWeight(.bold)
            .font(.title)
            .fontWeight(.bold)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .multilineTextAlignment(.center)
            .padding()
          Text("Change 4 Good Inc. is a nonprofit based in Maryland whose purpose is to provide food and assistance to families in need and the homeless.")
            .font(.caption)
            .multilineTextAlignment(.center)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .fixedSize(horizontal: false, vertical: true)
            .padding()
          Text("Get Started: Visit https://www.c4-g.com/mission.html for more info!")
            .font(.caption)
            .multilineTextAlignment(.center)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .padding()
          Text("DoSomething Action: Tackle Hunger!")
            .font(.subheadline)
            .fontWeight(.bold)
            .font(.title)
            .fontWeight(.bold)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .multilineTextAlignment(.center)
            .padding()
          Text("DoSomething Action: Tackle Hunger! is an online organization who aims to spread awareness about food insecurity and donate food to your local food banks.")
            .font(.caption)
            .multilineTextAlignment(.center)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .fixedSize(horizontal: false, vertical: true)
            .padding()
          Text("Get Started: Visit https://dosomething.org/action/tackle-hunger for more info!")
            .font(.caption)
            .multilineTextAlignment(.center)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .padding()
          Text("Forgotten Harvest")
            .font(.subheadline)
            .fontWeight(.bold)
            .font(.title)
            .fontWeight(.bold)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .multilineTextAlignment(.center)
            .padding()
          Text("Forgotton Harvest is an organization based in Michigan that fights hunger and food insecurity.")
            .font(.caption)
            .multilineTextAlignment(.center)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .fixedSize(horizontal: false, vertical: true)
            .padding()
          Text("Get Started: Visit https://www.forgottenharvest.org/ for more info!")
            .font(.caption)
            .multilineTextAlignment(.center)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .padding()
          Text("Food Gatherers")
            .font(.subheadline)
            .fontWeight(.bold)
            .font(.title)
            .fontWeight(.bold)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .multilineTextAlignment(.center)
            .padding()
          Text("Food Gatherers is a food bank and food rescue program located in Michigan that operates multiple large direct service programs.")
            .font(.caption)
            .multilineTextAlignment(.center)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .fixedSize(horizontal: false, vertical: true)
            .padding()
          Text("Get Started: Visit https://www.foodgatherers.org/ for more info!")
            .font(.caption)
            .multilineTextAlignment(.center)
            .foregroundColor(Color(red: 109/255, green: 139/255, blue: 133/255, opacity: 1.0))
            .padding()
        }
      }
    }
  }
}
#Preview {
  Homeless()
}
